global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 2s

alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090

- job_name: http
  http_sd_configs:
      - url: "http://discovery:4848/discovery"
