---
- name: Stop public Mac CI runners
  hosts: public_m1_mac_runners

  pre_tasks:
    - import_tasks: utils/check_macos.yml

  tasks:
    - include_role:
        name: actions_daemon
        tasks_from: stop
