---
- name: Install a specific version of XCode
  hosts: "{{ host_param | default('m1_mac_runners') }}"

  pre_tasks:
    - import_tasks: utils/check_macos.yml

  tasks:
    - include_role:
        name: xcode_setup
